
#visite : http://docs.frrouting.org/en/latest/setup.html

# Enable routing daemons for P1
zebra=yes
bgpd=yes
ospfd=yes
isisd=yes

# Disable unused daemons
ospf6d=no
ripd=no
ripngd=no
pimd=no
ldpd=no
nhrpd=no
eigrpd=no
babeld=no
sharpd=no
pbrd=no
bfdd=no
fabricd=no
vrrpd=no
pathd=no